---
title: "agrammatism_exp7.3"
author: "Yi Wei"
date: "2025-03-05"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_knit$set(echo=TRUE)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	tidy = TRUE,
	tidy.opts = list(comment = FALSE)
)

library(tidyverse)
library(ggplot2)
library(lme4)
library(lmerTest)
# library(knitr)
# library(ggeffects)
# library(formatR)
# library(huxtable)
# library(modelsummary)
library(dplyr)
# library(readr)

# library(influence.ME)
# library(cowplot)
# library(corrplot)
library(emmeans)
# library(pbkrtest)

```

### get an general idea of the dataset

```{r read in files}

root_dir = "/Users/yiwei/Dropbox/agrammatism/MEGstudy/speechProductionData"

dataframes = list()

# Get all subdirectories starting with 'R'
subdirs <- list.dirs(root_dir, recursive = FALSE, full.names = TRUE)
subdirs <- subdirs[basename(subdirs) %>% startsWith("R")]

# Loop through each subdirectory
for (subdir in subdirs) {
  # Find all .csv files with 'responseOnsetTime' in their names
  csv_files <- list.files(subdir, pattern = "responseOnsetTime.*\\.csv$", full.names = TRUE)
  csv_files <- csv_files[!basename(csv_files) %>% startsWith("~$")]

  
  # Read each .csv file and append the data frame to the list
  for (csv_file in csv_files) {
    df <- read_csv(csv_file, show_col_types = FALSE)
    dataframes <- append(dataframes, list(df))
  }
}


# Concatenate all data frames into one
combined_df <- bind_rows(dataframes)

# Add the session column based on the filename
combined_df <- combined_df %>%
  mutate(session = case_when(
    grepl("IF", filename) ~ 'iconfirst',
    grepl("PF", filename) ~ 'picturefirst',
    TRUE ~ NA_character_
    )) %>%
  mutate(wordCat = case_when(
    wordType %in% c('nouncontrol', 'nounnm', 'nounpp', 'nounpc') ~ 'noun',
    wordType %in% c('verbcontrol', 'verbnm', 'inffut', 'infpst') ~ 'verb',
    TRUE ~ NA_character_
    )) %>%
  mutate(verbType = case_when(
    trial %in% c(25, 42, 46, 61, 75, 101, 113, 126, 144, 174, 182, 214, 286, 316, 360) & (session == 'iconfirst') ~ 'irregular',
    trial %in% c(14, 75, 92, 96, 110, 161, 175, 216, 251, 263, 276, 294, 336, 374, 382) & (session == 'picturefirst')~ 'irregular',
    TRUE ~ NA_character_
    )) %>%
  mutate(verbType = case_when(
    !is.na(verbType) ~ verbType,
    wordCat == 'verb' ~ 'regular',
    TRUE ~ verbType
    )) %>%
  mutate(wordType2 = wordType) %>%
  mutate(wordType2 = case_when(
    (verbType == 'irregular') & (wordType == 'infpst') ~ 'infpstIrr',
    (verbType == 'regular') & (wordType == 'infpst') ~ 'infpstReg',
    TRUE ~ wordType2
  ))
    
```

```{r}

left_handed_subjects <- c('R3135', 'R3205', 'R3210')

filtered_data <- combined_df %>%
  filter(MFA_sentence_onset > 0.4 & !subject %in% left_handed_subjects & is.na(incorrect)) %>%
  mutate(MFA_sentence_onset = MFA_sentence_onset - 0.257) %>%
  filter(session == 'picturefirst')
filtered_data$wordType <- as.factor(filtered_data$wordType)

```


### build regression model
```{r}

emm_options(lmerTest.limit = 15000)
emm_options(pbkrtest.limit = 15000)

model_all <- lmer(MFA_sentence_onset~wordType+(1+wordType|subject), data = filtered_data)
anova(model_all)
summary(model_all)

```


```{r}

library(ggsignif)

# Perform post-hoc pairwise comparisons using emmeans
emmeans_results <- emmeans(model_all, pairwise ~ wordType)

# Create a data frame for plotting
emmeans_df <- as.data.frame(emmeans_results$emmeans)
contrasts_df <- as.data.frame(emmeans_results$contrasts)

```


```{r}

# Create a bar plot using ggplot2

emmeans_df$wordType <- factor(emmeans_df$wordType, levels = c("nouncontrol", "nounnm", "nounpp", "nounpc", "verbcontrol", "verbnm", "inffut", "infpst"))
# emmeans_df$wordType <- factor(emmeans_df$wordType, levels = c("nouncontrol", "nounnm", "nounpp", "nounpc", "verbcontrol", "verbnm", "inffut", "infpstReg","infpstIrr"))


p <- ggplot(emmeans_df, aes(x = wordType, y = emmean, fill = wordType)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.2, position = position_dodge(width = 0.9)) +
  labs(title = "MEG word onset time",
       x = "wordType",
       y = "Estimated Marginal Means of MFA onset time (s)") +
  theme_minimal() +
  ylim(0,5)

comparisons <- list()
annotations <- list()
# Add p-values as text annotations
for (i in 1:nrow(contrasts_df)) {
  contrast <- strsplit(as.character(contrasts_df$contrast[i]), " - ")[[1]]
  p_value <- contrasts_df$p.value[i]
  comparisons <- append(comparisons, list(contrast))
  annotations <- append(annotations, p_value)
}

# Initialize a counter for y_position increments
y_counter <- 0
for (i in seq_along(comparisons)) {
  comparison <- comparisons[[i]]
  p_value <- annotations[[i]]
  
  if (p_value > 0.05) {
    y_counter <- y_counter + 1
        y_position <- max(emmeans_df$upper.CL) + 0.3 * y_counter
    # Add the p-value annotation
    p <- p + geom_signif(
      comparisons = list(comparison),
      annotations = paste0("p = ", format(p_value, digits = 2)),
      y_position = y_position,
      tip_length = 0.2,
    )
  }
}

print(p)

# ggsave("/Users/yiwei/Dropbox/agrammatism/experiment2/in person data -0.75 lmer.pdf", height = 7, width = 5)

```
```{r}

model_noun <- lmer(MFA_sentence_onset~wordType+(1+wordType|subject), data = filtered_data, subset = (wordCat == 'noun'))
anova(model_noun)
summary(model_noun)

```


```{r}

library(ggsignif)

# Perform post-hoc pairwise comparisons using emmeans
emmeans_results_noun <- emmeans(model_noun, pairwise ~ wordType)

# Create a data frame for plotting
emmeans_df_noun <- as.data.frame(emmeans_results_noun$emmeans)
contrasts_df_noun <- as.data.frame(emmeans_results_noun$contrasts)

```


```{r}

# Create a bar plot using ggplot2

emmeans_df_noun$wordType <- factor(emmeans_df_noun$wordType, levels = c("nouncontrol", "nounnm", "nounpp", "nounpc"))
# emmeans_df$wordType <- factor(emmeans_df$wordType, levels = c("nouncontrol", "nounnm", "nounpp", "nounpc", "verbcontrol", "verbnm", "inffut", "infpstReg","infpstIrr"))


p <- ggplot(emmeans_df_noun, aes(x = wordType, y = emmean, fill = wordType)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.2, position = position_dodge(width = 0.9)) +
  labs(title = "MEG word onset time",
       x = "wordType",
       y = "Estimated Marginal Means of MFA onset time (s)") +
  theme_minimal() +
  ylim(0,2.5)

comparisons <- list()
annotations <- list()
# Add p-values as text annotations
for (i in 1:nrow(contrasts_df_noun)) {
  contrast <- strsplit(as.character(contrasts_df_noun$contrast[i]), " - ")[[1]]
  p_value <- contrasts_df_noun$p.value[i]
  comparisons <- append(comparisons, list(contrast))
  annotations <- append(annotations, p_value)
}

# Initialize a counter for y_position increments
y_counter <- 0
for (i in seq_along(comparisons)) {
  comparison <- comparisons[[i]]
  p_value <- annotations[[i]]
  
  if (p_value < 0.05) {
    y_counter <- y_counter + 1
        y_position <- max(emmeans_df_noun$upper.CL) + 0.3 * y_counter
    # Add the p-value annotation
    p <- p + geom_signif(
      comparisons = list(comparison),
      annotations = paste0("p = ", format(p_value, digits = 2)),
      y_position = y_position,
      tip_length = 0.2,
    )
  }
}

print(p)

# ggsave("/Users/yiwei/Dropbox/agrammatism/experiment2/in person data -0.75 lmer.pdf", height = 7, width = 5)

```

```{r}

model_verb <- lmer(MFA_sentence_onset~wordType2+(1+wordType2|subject), data = filtered_data, subset = (wordCat == 'verb'))
anova(model_verb)
summary(model_verb)

```



```{r}

library(ggsignif)

# Perform post-hoc pairwise comparisons using emmeans
emmeans_results_verb <- emmeans(model_verb, pairwise ~ wordType2)

# Create a data frame for plotting
emmeans_df_verb <- as.data.frame(emmeans_results_verb$emmeans)
contrasts_df_verb <- as.data.frame(emmeans_results_verb$contrasts)

```

```{r}

# Create a bar plot using ggplot2

# emmeans_df_verb$wordType <- factor(emmeans_df_verb$wordType, levels = c("verbcontrol", "verbnm", "inffut", "infpst"))
emmeans_df_verb$wordType2 <- factor(emmeans_df_verb$wordType2, levels = c("verbcontrol", "verbnm", "inffut", "infpstReg","infpstIrr"))



p <- ggplot(emmeans_df_verb, aes(x = wordType2, y = emmean, fill = wordType)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.2, position = position_dodge(width = 0.9)) +
  labs(title = "MEG word onset time",
       x = "wordType",
       y = "Estimated Marginal Means of MFA onset time (s)") +
  theme_minimal() +
  ylim(0,2.5)

comparisons <- list()
annotations <- list()
# Add p-values as text annotations
for (i in 1:nrow(contrasts_df_verb)) {
  contrast <- strsplit(as.character(contrasts_df_verb$contrast[i]), " - ")[[1]]
  p_value <- contrasts_df_verb$p.value[i]
  comparisons <- append(comparisons, list(contrast))
  annotations <- append(annotations, p_value)
}

# Initialize a counter for y_position increments
y_counter <- 0
for (i in seq_along(comparisons)) {
  comparison <- comparisons[[i]]
  p_value <- annotations[[i]]
  
  if (p_value < 0.05) {
    y_counter <- y_counter + 1
        y_position <- max(emmeans_df_verb$upper.CL) + 0.25 * y_counter
    # Add the p-value annotation
    p <- p + geom_signif(
      comparisons = list(comparison),
      annotations = paste0("p = ", format(p_value, digits = 2)),
      y_position = y_position,
      tip_length = 0.2,
    )
  }
}

print(p)

# ggsave("/Users/yiwei/Dropbox/agrammatism/experiment2/in person data -0.75 lmer.pdf", height = 7, width = 5)

```


